package string;

import java.util.Arrays;

public class FIndTheDIfference {
/*Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.*/
    public char findTheDifference(String s, String t) {
        char[] chararray=s.toCharArray();
        char[] chararray2=t.toCharArray();
        Arrays.sort(chararray);
        Arrays.sort(chararray2);
        
        for(int i=0;i<chararray.length;i++){
            if(chararray[i]!=chararray2[i]){
                return chararray2[i];
            }
        }
        return chararray2[chararray2.length-1];
        
    }
}
